# Generated by Django 5.1.1 on 2024-09-24 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0003_ingredient_remove_groceryitem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='grocery_app.ingredient'),
        ),
    ]
